In [4]:
import pandas as pd
import requests
import json

from google_play_scraper import Sort, reviews

In [5]:
result, continuation_token = reviews(
    'id.co.bri.brimo', # application unique tag in google playstore
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.NEWEST
    count=20, # defaults to 100
    filter_score_with=None # defaults to None(means all score)
)

df = pd.DataFrame(result)
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8d4330da-1eff-4fc6-b986-d15a59ce159e,Iyus Tini,https://play-lh.googleusercontent.com/a/ACg8oc...,Nyaman dan aman,5,0,2.63.0,2024-07-15 16:45:52,Terima kasih atas ulasannya. Semoga aplikasi B...,2024-07-15 17:10:28,2.63.0
1,d9bfc16b-2397-4259-bec2-7ddb71da0a87,Wahyudi Traknus,https://play-lh.googleusercontent.com/a-/ALV-U...,"Hore, akhirnya saya punya rekening & akun Bank...",5,0,2.63.0,2024-07-15 16:40:49,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 18:52:14,2.63.0
2,79f276a5-14bd-4af0-9c74-73562a5e7416,Ana Nia,https://play-lh.googleusercontent.com/a/ACg8oc...,Akhir2 ini kok susah yaa brimo nya kalo mau tf...,4,0,2.63.0,2024-07-15 16:32:26,None,NaT,2.63.0
3,1ac9f80f-9ad9-48bd-a730-61f62a4769b7,Akmal Akmal,https://play-lh.googleusercontent.com/a/ACg8oc...,lebih simpel pakenya,5,0,2.61.0,2024-07-15 16:10:19,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:18,2.61.0
4,61640f8b-9c16-4af2-bf58-0629980dd70d,Aulana Pramada,https://play-lh.googleusercontent.com/a/ACg8oc...,Mantap,5,0,2.63.0,2024-07-15 16:10:16,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:16,2.63.0
5,6392a95e-5c9a-45b0-ab2c-47b008ec121b,Ariff Setiawann,https://play-lh.googleusercontent.com/a/ACg8oc...,Jadi lebih gapang,5,0,2.52.0,2024-07-15 16:09:53,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:14,2.52.0
6,ac5a69fc-9bf0-4ea1-9d61-20d897058f63,Merry Maniku,https://play-lh.googleusercontent.com/a/ACg8oc...,Cepat and mudah,5,0,2.63.0,2024-07-15 16:08:54,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:13,2.63.0
7,e9dff493-5f30-42f3-af86-0b6c66af3d9d,Khoiron M,https://play-lh.googleusercontent.com/a-/ALV-U...,Kenpa punya saya gak bisa masuk ya skrng pasti...,1,0,2.63.0,2024-07-15 16:05:27,"Sobat BRI, mohon maaf atas ketidaknyamanan yan...",2024-07-15 19:51:21,2.63.0
8,11a7c228-1a77-4907-a66a-4a84a35a3837,Rama prayoga,https://play-lh.googleusercontent.com/a-/ALV-U...,Okeee,5,0,None,2024-07-15 16:04:15,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:10,None
9,582a89e7-6ff0-48e1-802d-b1204a11db65,Nurazzahra Widhi,https://play-lh.googleusercontent.com/a-/ALV-U...,Bs dg cpt bertansaksi,5,0,2.63.0,2024-07-15 16:03:48,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:09,2.63.0
10,9632833f-7438-41f2-b7eb-870522efd8d3,Ikbal Maulana,https://play-lh.googleusercontent.com/a-/ALV-U...,Mudah belanja tranfer,5,0,2.63.0,2024-07-15 16:01:29,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:08,2.63.0
11,aa2d95d4-32ea-4527-b0fc-0a838ebdd92f,Rudy Karyono,https://play-lh.googleusercontent.com/a-/ALV-U...,Mantap,5,0,2.63.0,2024-07-15 15:58:43,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:06,2.63.0
12,c624db06-ecf2-44c0-a6c1-7af8bbfa20a5,AS EF,https://play-lh.googleusercontent.com/a-/ALV-U...,Alhamdulillah selama penggunaan nya belum ada ...,4,0,2.63.0,2024-07-15 15:58:12,None,NaT,2.63.0
13,e221e986-78ca-4a0a-8344-f8b340e4d8b7,felly hamdani,https://play-lh.googleusercontent.com/a/ACg8oc...,-Mudah dan cepat prosesnya -Sangat membantu se...,5,0,2.63.0,2024-07-15 15:57:50,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:05,2.63.0
14,94f63df0-624c-4351-9af6-9e3fe28a743a,Irfan Pramana,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus dan sangat memudahkan segala transaksi 👍...,5,0,2.59.0,2024-07-15 15:57:22,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:03,2.59.0
15,08c93341-9499-4d97-8221-55ec47bd068f,Turu Bujanginam,https://play-lh.googleusercontent.com/a-/ALV-U...,Luar biasa,5,0,2.63.0,2024-07-15 15:56:43,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:03,2.63.0
16,895cc756-37ff-4f04-a70b-50dc5ced805c,Botz O'cs,https://play-lh.googleusercontent.com/a/ACg8oc...,di permudah,5,0,2.62.0,2024-07-15 15:55:29,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:17:00,2.62.0
17,c3348fb5-0276-425f-afa7-ca652f46ef4b,Timbul Johannes,https://play-lh.googleusercontent.com/a-/ALV-U...,good,5,0,2.63.0,2024-07-15 15:54:46,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:16:59,2.63.0
18,3f5a772f-ad1a-44f4-9c18-d07c4791605d,Titin Cookies,https://play-lh.googleusercontent.com/a/ACg8oc...,manttull,5,0,None,2024-07-15 15:48:11,Terima kasih atas ulasannya. Semoga aplikasi B...,2024-07-15 16:20:44,None
19,733ae004-1fab-4ae0-a06f-7cebecdca5d5,Imas May,https://play-lh.googleusercontent.com/a-/ALV-U...,Mempermudah transaksi apapun,5,0,2.63.0,2024-07-15 15:46:28,"Hai Sobat BRI, terima kasih atas ulasannya. Se...",2024-07-15 16:16:56,2.63.0

In [6]:
def review_analyze(text):
    payload = {
        "model" : "llama3",
        "messages" : [
            {"role" : "system",
             "content":f"""
                You are an expert in analyzing user reviews. Identify the key topics and sentiments of the following Playstore review for the BRImo mobile banking app by Bank Rakyat Indonesia, one of Indonesia's most reputable banks. Summarize the review and provide its sentiment.
                 """},
            {"role" : "user",
             "content": f"""
                Question: Identify the key topics of this playstore review for a mobile banking app of BRI (Bank Rakyat Indonesia) 
                          called BRImo which is one of the most reputable bank in Indonesia and what is the sentiments of these review?

                Review: "{text}"   

                Thought 1: Understand the content of the review and identify its key topics.
                Action 1: Analyze the review text to extract key topics.
                Observation 1: The key topics are...
                
                Thought 2: Analyze the tone and language of the review.
                Action 2: Determine the sentiment of the review text.
                Observation 2: The review text indicates positive/negative/neutral sentiment.

                Conclusion: Summarize the key topics and sentiment of the review using this format AND NOTHING ELSE BESIDES THIS: 
                - Topic (1 or 2 words that describe the topic of the review, Fill with 'Overall' if the review doesn't mention anything specifically)
                - Sentiment (Negative, Neutral, or Positive)
                - Explanation (1 to 2 sentence, explain briefly the analysis) 

                Return your answer in JSON format.
                """}
        ] 
    }

    analysis_result = ""
    response = requests.post("http://localhost:11434/api/chat", json=payload)
    for message in response.iter_lines():
        jsonstr = json.loads(message)
        llm_answer = jsonstr["message"]["content"]
        analysis_result += llm_answer
    
    return analysis_result

    
results = []
for i, row in df.iterrows():
    review_id = row['reviewId']
    username = row['userName']
    datetime = row['at']
    rating = row['score']
    review_content = row['content']
    analysis = review_analyze(review_content)
    results.append({"review_id": review_id, "username": username, "datetime":datetime, "rating":rating, 
                    "review": review_content, "analysis": analysis})

results_df = pd.DataFrame(results)

In [ ]:
results_df.drop('analysis')

,username,datetime,rating,review,analysis
0,Akmal Akmal,2024-07-15 16:10:19,5,lebih simpel pakenya,"{\n""Topic"": ""Ease"",\n""Sentiment"": ""Positive"",\..."
1,Aulana Pramada,2024-07-15 16:10:16,5,Mantap,"{\n""Topic"": ""Appreciation"",\n""Sentiment"": ""Pos..."
2,Ariff Setiawann,2024-07-15 16:09:53,5,Jadi lebih gapang,"{\n""Topic"": ""Satisfaction"",\n""Sentiment"": ""Pos..."
3,Merry Maniku,2024-07-15 16:08:54,5,Cepat and mudah,"{\n""Topic"": ""User Experience"",\n""Sentiment"": ""..."
4,Khoiron M,2024-07-15 16:05:27,1,Kenpa punya saya gak bisa masuk ya skrng pasti...,"{\n""Topic"": ""Login Issues"",\n""Sentiment"": ""Neg..."
5,Rama prayoga,2024-07-15 16:04:15,5,Okeee,"{\n""Topic"": ""Simple"",\n""Sentiment"": ""Positive""..."
6,Nurazzahra Widhi,2024-07-15 16:03:48,5,Bs dg cpt bertansaksi,"{\n""Topic"": ""Transaction"",\n""Sentiment"": ""Posi..."
7,Ikbal Maulana,2024-07-15 16:01:29,5,Mudah belanja tranfer,"{\n""Topic"": ""Easy Transfer"",\n""Sentiment"": ""Po..."
8,Rudy Karyono,2024-07-15 15:58:43,5,Mantap,"{\n""Topic"": ""Appraisal"",\n""Sentiment"": ""Positi..."
9,AS EF,2024-07-15 15:58:12,4,Alhamdulillah selama penggunaan nya belum ada ...,"{\n""Topic"": ""App Performance"",\n""Sentiment"": ""..."
10,felly hamdani,2024-07-15 15:57:50,5,-Mudah dan cepat prosesnya -Sangat membantu se...,"{\n""Topic"": ""User Experience"",\n""Sentiment"": ""..."
11,Irfan Pramana,2024-07-15 15:57:22,5,bagus dan sangat memudahkan segala transaksi 👍...,"{\n""Topic"": ""Ease of use"",\n""Sentiment"": ""Posi..."
12,Turu Bujanginam,2024-07-15 15:56:43,5,Luar biasa,"{\n""Topic"": ""Exceptional"",\n""Sentiment"": ""Posi..."
13,Botz O'cs,2024-07-15 15:55:29,5,di permudah,"{\n""Topic"": ""User Experience"",\n""Sentiment"": ""..."
14,Timbul Johannes,2024-07-15 15:54:46,5,good,"{\n""Topic"": ""General"",\n""Sentiment"": ""Positive..."
15,Titin Cookies,2024-07-15 15:48:11,5,manttull,"{\n""Topic"": ""Overall"",\n""Sentiment"": ""Positive..."
16,Imas May,2024-07-15 15:46:28,5,Mempermudah transaksi apapun,"{\n""Topic"": ""Ease of Transaction"",\n""Sentiment..."
17,Akmad Tomo,2024-07-15 15:44:00,3,Ko d hp Oppo a16 saya ga bisa buka apk brimo y...,"{\n""Topic"": ""App Error"",\n""Sentiment"": ""Negati..."
18,Parluhutan Siburian,2024-07-15 15:42:56,5,Yupz,"{\n""Topic"": ""Overall"",\n""Sentiment"": ""Positive..."
19,Ikhsyan ʍǟʀաǟռ,2024-07-15 15:39:28,5,Ok,"{\n""Topic"": ""Overall"",\n""Sentiment"": ""Neutral""..."

In [ ]:
print(results_df.iloc[0,:]['analysis'])

{
"Topic": "Ease",
"Sentiment": "Positive",
"Explanation": "The review mentions 'lebih simpel pakenya' which translates to 'it's easier to use', indicating that the reviewer finds the app easy to navigate and use."
}

In [ ]:
# Function to parse the JSON-like string
def parse_json_column(json_str):
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return {"Topics": None, "Sentiment": None, "Explanation": None}

# Apply the function to parse the column
parsed_column = results_df["analysis"].apply(parse_json_column)

# Convert the parsed column to a DataFrame
parsed_df = pd.json_normalize(parsed_column)

# Concatenate the new DataFrame with the original DataFrame
results_df = pd.concat([results_df, parsed_df], axis=1)
results_df

,username,datetime,rating,review,analysis,Topic,Sentiment,Explanation
0,Akmal Akmal,2024-07-15 16:10:19,5,lebih simpel pakenya,"{\n""Topic"": ""Ease"",\n""Sentiment"": ""Positive"",\...",Ease,Positive,The review mentions 'lebih simpel pakenya' whi...
1,Aulana Pramada,2024-07-15 16:10:16,5,Mantap,"{\n""Topic"": ""Appreciation"",\n""Sentiment"": ""Pos...",Appreciation,Positive,The review only contains a single word 'Mantap...
2,Ariff Setiawann,2024-07-15 16:09:53,5,Jadi lebih gapang,"{\n""Topic"": ""Satisfaction"",\n""Sentiment"": ""Pos...",Satisfaction,Positive,The review contains the phrase 'Jadi lebih gap...
3,Merry Maniku,2024-07-15 16:08:54,5,Cepat and mudah,"{\n""Topic"": ""User Experience"",\n""Sentiment"": ""...",User Experience,Positive,"The review mentions 'Cepat' and 'mudah', which..."
4,Khoiron M,2024-07-15 16:05:27,1,Kenpa punya saya gak bisa masuk ya skrng pasti...,"{\n""Topic"": ""Login Issues"",\n""Sentiment"": ""Neg...",Login Issues,Negative,The reviewer mentions they can't log in and bl...
5,Rama prayoga,2024-07-15 16:04:15,5,Okeee,"{\n""Topic"": ""Simple"",\n""Sentiment"": ""Positive""...",Simple,Positive,The reviewer's brief and positive response sug...
6,Nurazzahra Widhi,2024-07-15 16:03:48,5,Bs dg cpt bertansaksi,"{\n""Topic"": ""Transaction"",\n""Sentiment"": ""Posi...",Transaction,Positive,The review is short and does not provide speci...
7,Ikbal Maulana,2024-07-15 16:01:29,5,Mudah belanja tranfer,"{\n""Topic"": ""Easy Transfer"",\n""Sentiment"": ""Po...",Easy Transfer,Positive,The review mentions that transferring money is...
8,Rudy Karyono,2024-07-15 15:58:43,5,Mantap,"{\n""Topic"": ""Appraisal"",\n""Sentiment"": ""Positi...",Appraisal,Positive,The single-word review 'Mantap' is an Indonesi...
9,AS EF,2024-07-15 15:58:12,4,Alhamdulillah selama penggunaan nya belum ada ...,"{\n""Topic"": ""App Performance"",\n""Sentiment"": ""...",App Performance,Positive,The reviewer mentions that they have not exper...
10,felly hamdani,2024-07-15 15:57:50,5,-Mudah dan cepat prosesnya -Sangat membantu se...,"{\n""Topic"": ""User Experience"",\n""Sentiment"": ""...",User Experience,Positive,The review mentions that the process is easy a...
11,Irfan Pramana,2024-07-15 15:57:22,5,bagus dan sangat memudahkan segala transaksi 👍...,"{\n""Topic"": ""Ease of use"",\n""Sentiment"": ""Posi...",Ease of use,Positive,The reviewer uses superlatives such as 'bagus'...
12,Turu Bujanginam,2024-07-15 15:56:43,5,Luar biasa,"{\n""Topic"": ""Exceptional"",\n""Sentiment"": ""Posi...",Exceptional,Positive,The review contains only one word 'Luar biasa'...
13,Botz O'cs,2024-07-15 15:55:29,5,di permudah,"{\n""Topic"": ""User Experience"",\n""Sentiment"": ""...",User Experience,Positive,The review contains the Indonesian phrase 'di ...
14,Timbul Johannes,2024-07-15 15:54:46,5,good,"{\n""Topic"": ""General"",\n""Sentiment"": ""Positive...",General,Positive,The review is extremely brief and only contain...
15,Titin Cookies,2024-07-15 15:48:11,5,manttull,"{\n""Topic"": ""Overall"",\n""Sentiment"": ""Positive...",Overall,Positive,The review is very brief and does not mention ...
16,Imas May,2024-07-15 15:46:28,5,Mempermudah transaksi apapun,"{\n""Topic"": ""Ease of Transaction"",\n""Sentiment...",Ease of Transaction,Positive,The review mentions that the app makes transac...
17,Akmad Tomo,2024-07-15 15:44:00,3,Ko d hp Oppo a16 saya ga bisa buka apk brimo y...,"{\n""Topic"": ""App Error"",\n""Sentiment"": ""Negati...",App Error,Negative,The review mentions that the reviewer is unabl...
18,Parluhutan Siburian,2024-07-15 15:42:56,5,Yupz,"{\n""Topic"": ""Overall"",\n""Sentiment"": ""Positive...",Overall,Positive,The review consists of a single positive emoti...
19,Ikhsyan ʍǟʀաǟռ,2024-07-15 15:39:28,5,Ok,"{\n""Topic"": ""Overall"",\n""Sentiment"": ""Neutral""...",Overall,Neutral,"The review consists of a single word 'Ok', whi..."

In [ ]:
results_df.to_csv('results.csv', index=False)